### ISSUE TITLE
Create DNS entry for my PODS

### ISSUE THREAD

**Issue by nevetsgit** [LittlePath/bunchastories#2]
As a group desiring to set up video conferencing,
I want to set up a domain for my group
So that my group can participate in video conferences.

## Tech Notes

* Create a DNS entry for steven.littlepath.org

## Acceptance Criteria

Given I have navigated to the site that allows me to create a new online domain
When I follow the instructions for creating the domain
Then I should see:

* a page showing my group's domain
* a URL that my colleagues can access

For example: https://steven.littlepath.org or https://stevenwilhelm.inrupt.net

**Comment by scottdavis99** [comment]
Acceptance Criteria: https://scott.littlepath.org/

Scott Davis is managing these DNS entries. Reach out to him to set up add'l DNS entries for other PODS.
