### ISSUE TITLE
Obtain a TLS Security Certificate(s) for the domain name associated with the PODS

### ISSUE THREAD

**Issue by nevetsgit** [LittlePath/bunchastories#3]
As a owner of a PODS desiring to set up video conferencing,
I want to obtain appropriate security certificates for my PODS' domain name
So that my group can participate in video conferences securely

Tech Notes:
* This is a standard HTTPS/TLS certificate, issued from a standard certificate authority like Let's Encrypt https://letsencrypt.org/

Acceptance Criteria:

Given I have navigated to the site that allows me to obtain security certificates for my domain
When I follow the instructions for obtaining the certificates
Then I should see:
* a page showing my group's domain
* a URL that my colleagues can access

**Comment by scottdavis99** [comment]
Acceptance Criteria: https://scott.littlepath.org/

We are using Caddy2 web server, which, as long as it's running on a public-facing IP address with a DNS A record that points a domain name to the public IP address (scott.littlepath.org -> 1.2.3.4), we will always have a valid TLS certificate from Let's Encrypt. (Tech note: Caddy2 uses the ACME v2 protocol to provision TLS certs)
